import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Separator } from '@radix-ui/react-separator';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="container mx-auto py-6">
          <h1 className="text-3xl font-bold tracking-tight mb-1">Мой Минималистичный Блог</h1>
          <p className="text-muted-foreground">Заметки о веб-разработке, React, Next.js и Python</p>
          <Separator className="my-6" />
        </header>
        {children}
      </body>
    </html>
  );
}
